recipe: default.v1
language: zh
assistant_id: atguigu_ecs

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: qwen  # 确保这里使用正确的模型组
  flow_retrieval:
    active: false # 禁用流程检索

policies:
  - name: FlowPolicy
#  - name: IntentlessPolicy