recipe: default.v1
assistant_id: atguigu_ecs
language: zh

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: qwen

policies:
- name: FlowPolicy
- name: IntentlessPolicy
  llm:
    model_group: openai-gpt-4o
  embeddings:
    model_group: openai-embeddings
